
#server:
  #port: ${PORT:8000}
  

#eureka:
  #client:
  #  serviceUrl:
    #  defaultZone: http://localhost:1111/eureka/

#spring:
  #jpa:
   # generate-ddl: true
   # database: mysql
    #show-sql: true
   # hibernate:
   #  ddl-auto: update 
 # datasource:
  #  platform: mysql
  #  url: jdbc:mysql://localhost:3306/inspiratti_entity?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
   ## password:
  #application:
   # name: auth-server
 

# Discovery Server Access
#eureka:
 #   client:
  #    serviceUrl:
   #     defaultZone: http://localhost:1111/eureka/
   
   
   
